# Generated by Django 5.2.7 on 2025-10-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingrecipient",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
