# Generated by Django 5.2.7 on 2025-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0002_alter_mailingrecipient_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_date",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
    ]
