# Generated by Django 5.2.7 on 2025-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("message_sender", "0003_alter_mailing_end_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailingRecipient",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="clients.mailingrecipient"),
        ),
    ]
