# Generated by Django 5.2.7 on 2025-11-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0004_delete_mailingrecipient_alter_mailing_recipients"),
        ("messages_for_clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="messages_for_clients.message",
            ),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
