# Generated by Django 5.2.7 on 2025-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0005_alter_mailing_message_delete_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
