# Generated by Django 5.2.7 on 2025-11-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_mailingrecipient_email"),
        ("message_sender", "0006_alter_mailing_end_date_alter_mailing_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="clients.mailingrecipient", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                ],
                max_length=10,
            ),
        ),
    ]
