# Generated by Django 5.2.7 on 2025-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0007_alter_mailing_recipients_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
