# Generated by Django 5.2.7 on 2025-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0008_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_date",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
    ]
