# Generated by Django 5.2.7 on 2025-11-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0011_alter_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_date"],
                "permissions": [("can_view_all_mailings", "Сan view all mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
