# Generated by Django 5.2.7 on 2025-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0012_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_hidden",
            field=models.BooleanField(
                default=True, verbose_name="Статус отображения рассылки"
            ),
            preserve_default=False,
        ),
    ]
