# Generated by Django 5.2.7 on 2025-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0013_mailing_is_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="is_hidden",
            field=models.BooleanField(
                default=True, verbose_name="Статус отображения рассылки"
            ),
        ),
    ]
