# Generated by Django 5.2.7 on 2025-11-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0014_alter_mailing_is_hidden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_date"],
                "permissions": [
                    ("can_view_all_mailings", "Сan view all mailings"),
                    ("can_hide_mailing", "Can hide the mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
