# Generated by Django 5.2.7 on 2025-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Электронная почта получателя"
            ),
        ),
    ]
