# Generated by Django 5.2.7 on 2025-11-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_mailingrecipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "permissions": [("can_view_all_clients", "Сan view all clients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
